DROP TABLE IF EXISTS "manage";
DROP TABLE IF EXISTS "officiate";
DROP TABLE IF EXISTS "play";
DROP TABLE IF EXISTS "gameTeamStats";
DROP TABLE IF EXISTS "gameTeamInfo";
DROP TABLE IF EXISTS "playoffGames";
DROP TABLE IF EXISTS "gamePlayerStats";
DROP TABLE IF EXISTS "draftInfo";
DROP TABLE IF EXISTS "teach"; 
DROP TABLE IF EXISTS "coaches";
DROP TABLE IF EXISTS "games";
DROP TABLE IF EXISTS "seasons";
DROP TABLE IF EXISTS "teams";
DROP TABLE IF EXISTS "division";
DROP TABLE IF EXISTS "players";
DROP TABLE IF EXISTS "stadiums";
DROP TABLE IF EXISTS "locations";
DROP TABLE IF EXISTS "officials";
-- delete from teach;
-- delete from playoffGames;
-- delete from gameTeamStats;
-- delete from gameTeamInfo;
-- delete from gamePlayerStats;
-- delete from manage;
-- delete from play;
-- delete from draftInfo;
-- delete from games;
-- delete from seasons;
-- delete from officiate;
-- delete from teams;
-- delete from stadiums;
-- delete from locations;
-- delete from division
-- delete from players;
-- delete from officials;
-- delete from coaches;
-- DECLARE @sql NVARCHAR(MAX) = N'' SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + N' DROP CONSTRAINT ' + QUOTENAME(name) + N';' + CHAR(13) + CHAR(10) FROM sys.foreign_keys;
-- EXEC sp_executesql @sql;