# sql: 
# 	javac -cp sqlite-jdbc.jar project.java
# 	java -cp .:sqlite-jdbc.jar project 

msql:
	javac -cp mssql-jdbc-11.2.0.jre18.jar project.java
	java -cp .:mssql-jdbc-11.2.0.jre18.jar project

clean: 
	rm project.class
	rm MyDatabase.class
	rm pagination.class
